export interface SchemaModelSnapshot {
  model: string;
  table: string;
  scalarFields: readonly string[];
  relationFields: readonly string[];
  indexSnippets: readonly string[];
}

export const PRELAUNCH_SCHEMA_SNAPSHOT = [
  {
    model: 'Company',
    table: 'companies',
    scalarFields: [
      'id Int @id @default(autoincrement())',
      'companyName String @map("company_name")',
      'managerName String @map("manager_name")',
      'username String @unique',
      'passwordHash String @map("password_hash")',
      'businessRegistrationNumber String @map("business_registration_number")',
      'webhardAccess Boolean @default(true) @map("webhard_access")',
      'laserOnly Boolean @default(false) @map("laser_only")',
      'isApproved Boolean @default(false) @map("is_approved")',
      'driveRootFolderId String? @map("drive_root_folder_id")',
      'driveProvisioningStatus DriveProvisioningStatus @default(PENDING) @map("drive_provisioning_status")',
      'deletedAt DateTime? @map("deleted_at")',
    ],
    relationFields: [
      'files WebhardFile[]',
      'folders WebhardFolder[]',
      'folderAliases CompanyFolderAlias[]',
      'contacts Contact[]',
      'passwordResetTokens PasswordResetToken[]',
    ],
    indexSnippets: [
      '@@index([username])',
      '@@index([companyName])',
      '@@index([status, deletedAt])',
      '@@index([driveProvisioningStatus])',
    ],
  },
  {
    model: 'WebhardFile',
    table: 'webhard_files',
    scalarFields: [
      'id String @id @default(uuid())',
      'name String',
      'originalName String @map("original_name")',
      'size BigInt',
      'mimeType String @map("mime_type")',
      'path String',
      'folderId String? @map("folder_id")',
      'companyId Int? @map("company_id")',
      'uploadedBy String @map("uploaded_by")',
      'inquiryNumber String? @map("inquiry_number")',
      'isDownloaded Boolean @default(false) @map("is_downloaded")',
      'storageProvider StorageProvider @default(GOOGLE_DRIVE) @map("storage_provider")',
      'driveFileId String? @map("drive_file_id")',
      'driveMimeType String? @map("drive_mime_type")',
    ],
    relationFields: [
      'folder WebhardFolder? @relation(fields: [folderId], references: [id])',
      'company Company? @relation(fields: [companyId], references: [id])',
    ],
    indexSnippets: [
      '@@index([folderId])',
      '@@index([companyId])',
      '@@index([folderId, deletedAt])',
      '@@index([driveFileId])',
      '@@index([storageProvider])',
    ],
  },
  {
    model: 'WebhardFolder',
    table: 'webhard_folders',
    scalarFields: [
      'id String @id @default(uuid())',
      'parentId String? @map("parent_id")',
      'companyId Int? @map("company_id")',
      'contactId String? @map("contact_id") @db.Uuid',
      'folderKind String @default("generic") @map("folder_kind") @db.VarChar(20)',
      'storageProvider StorageProvider @default(GOOGLE_DRIVE) @map("storage_provider")',
      'driveFolderId String? @map("drive_folder_id")',
    ],
    relationFields: [
      'parent WebhardFolder? @relation("FolderHierarchy", fields: [parentId], references: [id])',
      'children WebhardFolder[] @relation("FolderHierarchy")',
      'files WebhardFile[]',
      'company Company? @relation(fields: [companyId], references: [id])',
    ],
    indexSnippets: [
      '@@index([parentId])',
      '@@index([companyId])',
      '@@index([contactId], map: "webhard_folders_contact_id_idx")',
      '@@index([driveFolderId])',
      '@@index([storageProvider])',
    ],
  },
  {
    model: 'Task',
    table: 'tasks',
    scalarFields: [
      'id String @id @default(uuid())',
      'contactId BigInt? @map("contact_id")',
      'title String @db.VarChar(255)',
      'taskType String? @map("task_type") @db.VarChar(50)',
      'status String @default("pending") @db.VarChar(20)',
      'priority String @default("normal") @db.VarChar(10)',
      'machineId String? @map("machine_id")',
      'orderId String? @map("order_id")',
      'sortOrder Int @default(0) @map("sort_order")',
    ],
    relationFields: [
      'machine Machine? @relation(fields: [machineId], references: [id], onDelete: SetNull)',
      'order Order? @relation("OrderTasks", fields: [orderId], references: [id], onDelete: SetNull)',
    ],
    indexSnippets: [
      '@@index([status])',
      '@@index([orderId])',
      '@@index([status, priority, sortOrder])',
    ],
  },
  {
    model: 'ErpWorker',
    table: 'erp_workers',
    scalarFields: [
      'id String @id @default(uuid())',
      'name String @db.VarChar(100)',
      'pinHash String @map("pin_hash") @db.VarChar(255)',
      'role String @default("field_worker") @db.VarChar(20)',
      'workerType String? @map("worker_type") @db.VarChar(20)',
      'isActive Boolean @default(true) @map("is_active")',
      'allowedIps String[] @default([]) @map("allowed_ips")',
      'lastLoginAt DateTime? @map("last_login_at")',
    ],
    relationFields: ['accessLogs WorkerAccessLog[]'],
    indexSnippets: ['@@index([isActive])', '@@index([role])'],
  },
  {
    model: 'Order',
    table: 'orders',
    scalarFields: [
      'id String @id @default(uuid())',
      'contactId BigInt? @map("contact_id")',
      'inquiryNumber String? @map("inquiry_number")',
      'companyName String @map("company_name") @db.VarChar(200)',
      'title String @db.VarChar(500)',
      'orderType String @default("standard") @map("order_type") @db.VarChar(30)',
      'status String @default("inquiry_received") @db.VarChar(30)',
      'productionStatus String? @map("production_status") @db.VarChar(30)',
      'confirmationStatus String? @map("confirmation_status") @db.VarChar(30)',
      'classificationStatus String? @map("classification_status") @db.VarChar(30)',
      'nestingStatus String? @map("nesting_status") @db.VarChar(30)',
      'billingStatus String? @map("billing_status") @db.VarChar(30)',
      'priority String @default("normal") @db.VarChar(10)',
      'webhardFolderId String? @map("webhard_folder_id")',
      'dxfClassifiedCount Int @default(0) @map("dxf_classified_count")',
      'nestingSheetCount Int? @map("nesting_sheet_count")',
      'updatedAt DateTime @default(now()) @updatedAt @map("updated_at")',
    ],
    relationFields: [
      'events OrderEvent[]',
      'jobEvents JobEvent[]',
      'tasks Task[] @relation("OrderTasks")',
      'deliveries Delivery[]',
      'nestingTasks NestingTask[]',
    ],
    indexSnippets: [
      '@@index([contactId])',
      '@@index([status])',
      '@@index([productionStatus])',
      '@@index([confirmationStatus])',
      '@@index([classificationStatus])',
      '@@index([nestingStatus])',
      '@@index([billingStatus])',
      '@@index([companyName])',
      '@@index([inquiryNumber])',
      '@@index([priority, status])',
    ],
  },
  {
    model: 'OrderEvent',
    table: 'order_events',
    scalarFields: [
      'id String @id @default(uuid())',
      'orderId String @map("order_id")',
      'eventType String @map("event_type") @db.VarChar(50)',
      'fromStatus String? @map("from_status") @db.VarChar(30)',
      'toStatus String? @map("to_status") @db.VarChar(30)',
      'source String @db.VarChar(30)',
      'actorName String? @map("actor_name") @db.VarChar(100)',
      'data Json?',
    ],
    relationFields: [
      'order Order @relation(fields: [orderId], references: [id], onDelete: Cascade)',
    ],
    indexSnippets: ['@@index([orderId, createdAt])', '@@index([eventType])', '@@index([source])'],
  },
  {
    model: 'JobEvent',
    table: 'job_events',
    scalarFields: [
      'id String @id @default(uuid())',
      'idempotencyKey String @unique @map("idempotency_key") @db.VarChar(255)',
      'eventType String @map("event_type") @db.VarChar(100)',
      'eventVersion Int @map("event_version")',
      'sourceWorker String @map("source_worker") @db.VarChar(50)',
      'sourceVersion String? @map("source_version") @db.VarChar(50)',
      'orderId String? @map("order_id")',
      'contactId String? @map("contact_id") @db.Uuid',
      'inquiryNumber String? @map("inquiry_number") @db.VarChar(100)',
      'workNumber String? @map("work_number") @db.VarChar(100)',
      'jobId String? @map("job_id")',
      'integrationRunId String? @map("integration_run_id")',
      'workerLocalId String? @map("worker_local_id") @db.VarChar(255)',
      'result String @db.VarChar(20)',
      'occurredAt DateTime @map("occurred_at")',
      'receivedAt DateTime @default(now()) @map("received_at")',
      'durationMs Int? @map("duration_ms")',
      'processedCount Int? @map("processed_count")',
      'payload Json',
      'stateApplyStatus String @default("not_applicable") @map("state_apply_status") @db.VarChar(20)',
      'failureId String? @map("failure_id")',
      'orderEventId String? @map("order_event_id")',
      'createdAt DateTime @default(now()) @map("created_at")',
    ],
    relationFields: [
      'order Order? @relation(fields: [orderId], references: [id], onDelete: SetNull)',
      'integrationRun IntegrationRun? @relation(fields: [integrationRunId], references: [id], onDelete: SetNull)',
      'failure JobFailure? @relation("JobEventFailure", fields: [failureId], references: [id], onDelete: SetNull)',
      'lastEventForFailures JobFailure[] @relation("JobFailureLastEvent")',
    ],
    indexSnippets: [
      '@@index([orderId, occurredAt(sort: Desc)])',
      '@@index([contactId, occurredAt(sort: Desc)])',
      '@@index([inquiryNumber, occurredAt(sort: Desc)])',
      '@@index([workNumber, occurredAt(sort: Desc)])',
      '@@index([jobId, occurredAt(sort: Desc)])',
      '@@index([integrationRunId, occurredAt(sort: Desc)])',
      '@@index([sourceWorker, occurredAt(sort: Desc)])',
      '@@index([failureId])',
      '@@index([occurredAt(sort: Desc)])',
    ],
  },
  {
    model: 'ApiKey',
    table: 'api_keys',
    scalarFields: [
      'id String @id @default(uuid())',
      'name String @db.VarChar(100)',
      'keyHash String @map("key_hash") @db.VarChar(255)',
      'programType String @map("program_type") @db.VarChar(30)',
      'permissions String[] @default([])',
      'isActive Boolean @default(true) @map("is_active")',
      'lastUsedAt DateTime? @map("last_used_at")',
    ],
    relationFields: [],
    indexSnippets: ['@@index([keyHash])'],
  },
  {
    model: 'JobFailure',
    table: 'job_failures',
    scalarFields: [
      'id String @id @default(uuid())',
      'jobId String? @map("job_id")',
      'orderId String? @map("order_id")',
      'contactId String? @map("contact_id") @db.Uuid',
      'inquiryNumber String? @map("inquiry_number") @db.VarChar(100)',
      'workNumber String? @map("work_number") @db.VarChar(100)',
      'sourceWorker String @map("source_worker") @db.VarChar(50)',
      'eventType String? @map("event_type") @db.VarChar(100)',
      'errorCode String @map("error_code") @db.VarChar(100)',
      'message String? @db.Text',
      'retryable Boolean @default(false)',
      'retryCount Int @default(0) @map("retry_count")',
      'resolvedAt DateTime? @map("resolved_at")',
      'resolvedBy String? @map("resolved_by") @db.VarChar(100)',
      'resolutionNote String? @map("resolution_note") @db.Text',
      'lastEventId String? @map("last_event_id")',
      'metadata Json?',
      'createdAt DateTime @default(now()) @map("created_at")',
      'updatedAt DateTime @updatedAt @map("updated_at")',
    ],
    relationFields: [
      'events JobEvent[] @relation("JobEventFailure")',
      'lastEvent JobEvent? @relation("JobFailureLastEvent", fields: [lastEventId], references: [id], onDelete: SetNull)',
    ],
    indexSnippets: [
      '@@index([jobId, createdAt(sort: Desc)])',
      '@@index([orderId, createdAt(sort: Desc)])',
      '@@index([contactId, createdAt(sort: Desc)])',
      '@@index([inquiryNumber, createdAt(sort: Desc)])',
      '@@index([workNumber, createdAt(sort: Desc)])',
      '@@index([sourceWorker, resolvedAt, createdAt(sort: Desc)])',
      '@@index([retryable, resolvedAt, createdAt(sort: Desc)])',
      '@@index([lastEventId])',
    ],
  },
  {
    model: 'IntegrationRun',
    table: 'integration_runs',
    scalarFields: [
      'id String @id @default(uuid())',
      'workerType String @map("worker_type") @db.VarChar(50)',
      'sourceVersion String? @map("source_version") @db.VarChar(50)',
      'startedAt DateTime @default(now()) @map("started_at")',
      'finishedAt DateTime? @map("finished_at")',
      'result String @default("running") @db.VarChar(20)',
      'processedCount Int @default(0) @map("processed_count")',
      'failedCount Int @default(0) @map("failed_count")',
      'metadata Json?',
      'createdAt DateTime @default(now()) @map("created_at")',
      'updatedAt DateTime @updatedAt @map("updated_at")',
    ],
    relationFields: ['jobEvents JobEvent[]'],
    indexSnippets: [
      '@@index([workerType, startedAt(sort: Desc)])',
      '@@index([result, startedAt(sort: Desc)])',
      '@@index([finishedAt])',
    ],
  },
  {
    model: 'ProgramHeartbeat',
    table: 'program_heartbeats',
    scalarFields: [
      'id String @id @default(uuid())',
      'programType String @map("program_type") @db.VarChar(30)',
      'instanceName String @map("instance_name") @db.VarChar(100)',
      'status String @default("online") @db.VarChar(20)',
      'version String? @db.VarChar(20)',
      'hostname String? @db.VarChar(100)',
      'lastSeenAt DateTime @default(now()) @map("last_seen_at")',
      'metadata Json?',
    ],
    relationFields: [],
    indexSnippets: ['@@unique([programType, instanceName])'],
  },
  {
    model: 'SyncLog',
    table: 'sync_logs',
    scalarFields: [
      'id Int @id @default(autoincrement())',
      'filename String @db.VarChar(500)',
      'companyName String? @map("company_name") @db.VarChar(200)',
      'status String @db.VarChar(30)',
      'contactId Int? @map("contact_id")',
      'orderId String? @map("order_id")',
      'errorMessage String? @map("error_message")',
      'md5Hash String? @map("md5_hash") @db.VarChar(64)',
      'metadata Json?',
    ],
    relationFields: [],
    indexSnippets: ['@@index([createdAt])', '@@index([status])', '@@index([md5Hash])'],
  },
] as const satisfies readonly SchemaModelSnapshot[];
